### ISSUE TITLE
Action Items

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#33] opened 2015-04-09 18:26 UTC
This issue is for tracking specific action items coming out of the meeting. Actions should be posted as responses to this issue.

A few _potential_ action items based on the current dev-policy draft include:
1. Chartering the Node.js and io.js Release Line Working Groups (these are made up initially of the members of each of the two TCs)
2. Chartering the Convergence Working Group (made up of a subset of members from each of the two TCs).
3. Chartering the LTS Working Group (made up of a subset of members from each of the two TCs).

Once chartered, the Convergence Working Group would be tasked with finalizing the Development Policy document and the convergence plan for the two development streams; the LTS Working Group would be tasked with drafting the LTS Roadmap and LTS Release strategy.

**Comment by mikeal** [comment] 2015-04-09 18:29
### Native Abstractions

Today io.js has endorsed the use of `nan` by addon developers. Node.js has not endorsed it but, as far as I know, has no ready alternative. This will need to get reconciled.

**Comment by mikeal** [comment] 2015-04-09 18:31
I'm going to suggest that for this first meeting we simply table any issues that cannot reach a consensus for the next meeting (which we can schedule in a weeks time) rather than forcing anything to a vote today. That will give us some more time to think and try to iterate on a solution via GitHub Issues prior to the next meeting where, if it is still not resolved, we can go for a vote.

**Comment by jasnell** [comment] 2015-04-09 18:31
Agreed. We do not want to rabbit hole and get derailed. We need to set that expectation from the very start.

**Comment by jasnell** [comment] 2015-04-09 18:32
In fact, we might not want to have any vote at all today. If everyone is in agreement, then fine, if there is question, we note the concern, and table it for additional consideration and decision on the next call.

**Comment by mikeal** [comment] 2015-04-09 18:37
> In fact, we might not want to have any vote at all today. If everyone is in agreement, then fine, if there is question, we note the concern, and table it for additional consideration and decision on the next call.

If there is a debate to be had we should have the debate and get as much on the table as we can. Once it's clear that we're not moving towards a resolution we should just table it. Agreed that nothing should go to a vote today.

I believe that James and I are tasked with moderating. If at any time we feel like we've stopped making progress we'll speak up and note that the issue is tabled for now.

**Comment by jasnell** [comment] 2015-04-09 18:43
If the decision to form the Convergence and LTS WG's is made, we'll want to have each of the separate TC's nominate members from each project (even if they are involved in both projects). A combined list would be compiled and put up for review/decision on the next call.

**Comment by mikeal** [comment] 2015-04-09 18:47
> we'll want to have each of the separate TC's nominate members from each project

Let's do that nomination process in a GH issue after the meeting. Some people may not be able to make this meeting and I want to make sure they get included.

**Comment by jasnell** [comment] 2015-04-09 18:50
https://github.com/jasnell/dev-policy/issues/39 - Getting end-user feedback on the development policy needs to be a critical next step before finalizing. This definitely ought to be discussed on the call.

**Comment by jasnell** [comment] 2015-04-09 20:02
Items:
Add to principles: Node focus on small kernel
Collaborators: TJ .. understand the differences for responsibilities
  better definition of collaborator
Clarify Reversion Process
Doodle poll for next meeting

**Comment by Fishrock123** [comment] 2015-04-09 20:18
> Node focus on small kernel

Just want to clarify that is also a goal of io.js -- no controversy there. :)

**Comment by jasnell** [comment] 2015-04-09 20:20
From this point on, for me, "Node" == node.js + io.js :-)

**Closed as completed** 2018-03-19 17:31 UTC
